config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :drivers
  resources :parcels
  resources :customers  
  match 'driver_capture' => 'drivers#new', :via => :get
  match 'delivery_sheet' => 'customers#new', :via => :get
  match '/trace/:id' => 'parcels#trace', :via => :get
   root 'home#map'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  self.primary_key = "id"
  has_many :parcels
end

app/models/customer_parcel.rb
class CustomerParcel < ActiveRecord::Base
    belongs_to :customer
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  self.primary_key = "id"
  has_many :parcels
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
  self.primary_key = "id"
  belongs_to :customer
  #belongs_to :driver
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  belongs_to :driver
  
end

app/models/tracker_location.rb
class TrackerLocation < ActiveRecord::Base
end

app/models/tracker_parcel.rb
class TrackerParcel < ActiveRecord::Base
end

app/controllers/customers_controller.rb
require 'uuid'
class CustomersController < ApplicationController
  before_filter :set_customer_id, :only => [:new]
  
  def index
   @customers = Customer.all
  end

  def new
    @customer = Customer.new
    
  end

  def show
    @customer = Customer.find(params[:id])
    @parcels = Parcel.where(:customer_id => @customer.customer_id)
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update_attributes(customer_params)
      # Handle a successful update.
    else
      render 'edit'
    end
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    #@tracker = Tracker.new
    #@tracker.tracker_id = @customer.tracking_number 
    uuid = UUID.new
    @client_number = uuid.generate
    @customer.customer_id = @client_number 
    
    if @customer.save
      flash[:notice] = "Successfully saved customer."
      render :action => 'index'
    else
      render :action => 'new'
    end
  end


  private
  def customer_params
    params.require(:customer).permit(:name,:surname,:phone,:email,:address,:province,:city, :postal_code, :tracking_number)
  end

  def set_customer_id
    uuid = UUID.new
    @client_number = uuid.generate
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @drivers = Driver.all
  end

  def new
    @driver = Driver.new
  end

  def show
    @driver = Driver.find(params[:id])
  end

  def create
    @driver = Driver.new(driver_params)
    @driver_tracker = Tracker.new
    
    uuid = UUID.new
    @driver_number = uuid.generate
    @driver.driver_id = @driver_number
    @driver_tracker.tracker_id = @driver_number
    if @driver.save
      @driver_tracker.save
      flash[:notice] = "Successfully saved driver."
      render :action => 'index'
    else
      render :action => 'new'
    end
  end

  def update
    @driver = Driver.find(params[:id])
    if @driver.update_attributes(driver_params)
    # Handle a successful update.
    else
      render 'edit'
    end
  end

  def edit
    @driver = Driver.find(params[:id])
  end

  private
  def driver_params
    params.require(:driver).permit(:name,:surname,:phone,:email,:address,:province,:city, :postal_code,:driver_id, :bank_name, :branch_code, :account_holder, :account_number, :account_type  )
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!

  def map
    flash[:success ] = "Welcome to Trace Mates"
    #other alternatives are
    # flash[:warn ] = "Israel don't quite like warnings"
    #flash[:danger ] = "Naomi let the dog out!"
  end

end

app/controllers/parcels_controller.rb
require 'uuid'
require 'rest-client'
require 'json'

class ParcelsController < ApplicationController

  def index
    @parcels = Parcel.all
  end

  def new
    @drivers = Driver.all
    @customer_id = params[:customer_id]
    @customer = Customer.find(@customer_id)
    @parcel = Parcel.new
    
    uuid = UUID.new
    @tracking_number = uuid.generate
  end

  def show
    @parcel = Parcel.find(params[:id])
  end

  def edit
    @drivers = Driver.all
    @parcel = Parcel.find(params[:id])
  end

  def trace
    Parcel.where(:tracking_number => params[:id])
    response = RestClient.get 'http://tracemates.foodmates.co.za/services/rest/v1/tracemates.php', {params: {"function" => "get_tracker_locations", 'tracking_number' => '123456789'}}
    @data = JSON.parse(response.body)
    @locations = @data["data"]
  end
  
  
  def create
    @parcel = Parcel.new(parcel_params)

    uuid = UUID.new
    @tracking_number = uuid.generate
    @parcel.parcel_id = @tracking_number
    @parcel.customer_id = params[:parcel][:customer_id]
    @parcel.delivered_flag = 'f'
    @parcel.tracker_id = params[:parcel][:tracker_id]
    if @parcel.save
      flash[:notice] = "Successfully saved parcel."
      render :action => 'index'
    else
      render :action => 'new'
    end
  end


  def update
    @drivers = Driver.all
    @parcel = Parcel.find(params[:id])
    if @parcel.update_attributes(parcel_params)
    # Handle a successful update.
    else
      render 'edit'
    end
  end
  
  private
  def parcel_params
    params.require(:parcel).permit(:name,:parcel_details,:address,:province,:city, :postal_code, :tracking_number, :customer_id, :tracker_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parcel_helper.rb
module ParcelHelper
end

app/helpers/parcels_helper.rb
module ParcelsHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Trace Mates" %> </title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  
  <body class="nav-md">
    <div class="container body">
      <% flash.each do |key, value| %>
      <div align="center" id="flash" class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
      <%= render "partials/sidenav" %>
      <%= render "partials/topnav" %>
      
      <%= yield %>
      
      <%= render "partials/footer" %>
      <%= javascript_include_tag 'footermanifest', 'data-turbolinks-track' => true %>    
</body>
</html>

app/views/layouts/devise_layout_html.erb
<%# views/layouts/external_pages.html.erb %>

<!DOCTYPE html>
<html>
<head>
  <title>Trace Mates</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <link href="css/myStyle.css" rel="stylesheet"/>
  <script src="js/jquery-1.10.1.min.js"></script>

  <style>

    /*Devise flash*/
    .alert-error {
      background-color: #f2dede;
      border-color: #eed3d7;
      color: #b94a48;
      text-align: center;
    }

    .alert-alert {
      background-color: #f2dede;
      border-color: #eed3d7;
      color: #b94a48;
      text-align: center;
    }

    .alert-notice {
      background-color: #dff0d8;
      border-color: #d6e9c6;
      color: #468847;
      text-align: left;
    }
  </style>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body style="background:#F7F7F7;">

<div class="container body">

  <% flash.each do |key, value| %>
      <div align="center" id="flash" class="alert alert-<%= key %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <ul style="text-align: center">
          <l>
          <b> <%= value %>  </b>
          </l>
        </ul>
      </div>
  <% end %>


  <%= yield %>

</body>

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    <p>Copyright © 2016 <a href="#">TraceMates</a>, All Rights Reserved.</p>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_sidenav.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;">
        <a href="/" class="site_title"><i class="fa fa-forumbee"></i> <span>Trace Mates</span></a>
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag "profile_pic_placeholder.png", :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <span>Logged in as</span>
          <h2><%= current_admin.email %></h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br />
      
      <h3>&nbsp;</h3>
      
      <div class="clearfix"></div>
      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

        <div class="menu_section">
          <ul class="nav side-menu">
	    <li>
	      <a><i class="fa fa-home"></i>Home</a>	      
	    </li>	    
            <li>
	      <a><i class="fa fa-cab"></i> Drivers <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li>
		  <a href="/drivers/new">New Driver</a>
                </li>
                <li>
		  <a href="/drivers">List Drivers</a>
                </li>            
              </ul>
            </li>
            <li><a><i class="fa fa-users"></i> Customers <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="/customers/new">New Customer</a>
                </li>
                <li><a href="/customers">List Customers</a>
                </li>
              </ul>
            </li>
	    <li><a href="/parcels"><i class="fa fa-parcel"></i> List Parcels</a>
            <li><a href="/driver_capture"><i class="fa fa-edit"></i> Driver Capture</a>
            </li>
            <li><a href="/delivery_sheet"><i class="fa fa-table"></i> Delivery Sheet </a>
            </li>
            <li><a href="/"><i class="fa fa-search"></i> Trace & Track</a>
            </li>
            <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
          <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout">
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
      </div>
      <!-- /menu footer buttons -->
    </div>
  </div>

app/views/partials/_topnav.html.erb
<!-- top navigation -->
<div class="top_nav">
  
  <div class="nav_menu">
    <nav class="" role="navigation">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag "profile_pic_placeholder.png" %> <%= current_admin.email %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;">  Profile</a>
            </li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li>
              <a href="javascript:;">Help</a>
            </li>
            <!-- <li><a href="/logout"><i class="fa fa-sign-out pull-right"></i> Log Out</a> -->
	    <li><%= link_to "Sign out", destroy_admin_session_path, method: :delete %></li>
          </ul>
        </li>
	
        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                <span class="image">
                  <%= image_tag "img.jpg" %>
                </span>
                <span>
                  <span>John Smith</span>
		  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image">
                  <%= image_tag "img.jpg" %>
                </span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image">
                  <%= image_tag "img.jpg" %>
                </span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image">
                  <%= image_tag "img.jpg" %>
                </span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>	
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->