config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :drivers
  resources :parcels
  resources :customers  
  match 'driver_capture' => 'drivers#new', :via => :get
  match 'delivery_sheet' => 'customers#new', :via => :get
  match '/trace/:id' => 'parcels#trace', :via => :get
   root 'home#map'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  self.primary_key = "id"
  has_many :parcels
end

app/models/customer_parcel.rb
class CustomerParcel < ActiveRecord::Base
    belongs_to :customer
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  self.primary_key = "id"
  has_many :parcels
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
  self.primary_key = "id"
  belongs_to :customer
  #belongs_to :driver
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  belongs_to :driver
  
end

app/models/tracker_location.rb
class TrackerLocation < ActiveRecord::Base
end

app/models/tracker_parcel.rb
class TrackerParcel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  layout :layout_by_resource
  
  protected
  
  def layout_by_resource
    if devise_controller?
      "devise_layout_html"
    else
      "application"
    end
  end
end

app/controllers/customers_controller.rb
require 'uuid'
class CustomersController < ApplicationController
  before_filter :set_customer_id, :only => [:new]
  
  def index
   @customers = Customer.all
  end

  def new
    @customer = Customer.new
    
  end

  def show
    @customer = Customer.find(params[:id])
    @parcels = Parcel.where(:customer_id => @customer.customer_id)
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update_attributes(customer_params)
      # Handle a successful update.
    else
      render 'edit'
    end
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    #@tracker = Tracker.new
    #@tracker.tracker_id = @customer.tracking_number 
    uuid = UUID.new
    @client_number = uuid.generate
    @customer.customer_id = @client_number 
    
    if @customer.save
      flash[:notice] = "Successfully saved customer."
      render :action => 'index'
    else
      render :action => 'new'
    end
  end


  private
  def customer_params
    params.require(:customer).permit(:name,:surname,:phone,:email,:address,:province,:city, :postal_code, :tracking_number)
  end

  def set_customer_id
    uuid = UUID.new
    @client_number = uuid.generate
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @drivers = Driver.all
  end

  def new
    @driver = Driver.new
  end

  def show
    @driver = Driver.find(params[:id])
  end

  def create
    @driver = Driver.new(driver_params)
    @driver_tracker = Tracker.new
    
    uuid = UUID.new
    @driver_number = uuid.generate
    @driver.driver_id = @driver_number
    @driver_tracker.tracker_id = @driver_number
    if @driver.save
      @driver_tracker.save
      flash[:notice] = "Successfully saved driver."
      render :action => 'index'
    else
      render :action => 'new'
    end
  end

  def update
    @driver = Driver.find(params[:id])
    if @driver.update_attributes(driver_params)
    # Handle a successful update.
    else
      render 'edit'
    end
  end

  def edit
    @driver = Driver.find(params[:id])
  end

  private
  def driver_params
    params.require(:driver).permit(:name,:surname,:phone,:email,:address,:province,:city, :postal_code,:driver_id, :bank_name, :branch_code, :account_holder, :account_number, :account_type  )
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!

  def map
    flash[:success ] = "Welcome to Trace Mates"
    #other alternatives are
    # flash[:warn ] = "Israel don't quite like warnings"
    #flash[:danger ] = "Naomi let the dog out!"
  end

end

app/controllers/parcels_controller.rb
require 'uuid'
require 'rest-client'
require 'json'

class ParcelsController < ApplicationController

  def index
    @parcels = Parcel.all
  end

  def new
    @drivers = Driver.all
    @customer_id = params[:customer_id]
    @customer = Customer.find(@customer_id)
    @parcel = Parcel.new
    
    uuid = UUID.new
    @tracking_number = uuid.generate
  end

  def show
    @parcel = Parcel.find(params[:id])
  end

  def edit
    @drivers = Driver.all
    @parcel = Parcel.find(params[:id])
  end

  def trace
    Parcel.where(:tracking_number => params[:id])
    response = RestClient.get 'http://tracemates.foodmates.co.za/services/rest/v1/tracemates.php', {params: {"function" => "get_tracker_locations", 'tracking_number' => '123456789'}}
    @data = JSON.parse(response.body)
    @locations = @data["data"]
  end
  
  
  def create
    @parcel = Parcel.new(parcel_params)

    uuid = UUID.new
    @tracking_number = uuid.generate
    @parcel.parcel_id = @tracking_number
    @parcel.customer_id = params[:parcel][:customer_id]
    @parcel.delivered_flag = 'f'
    @parcel.tracker_id = params[:parcel][:tracker_id]
    if @parcel.save
      flash[:notice] = "Successfully saved parcel."
      render :action => 'index'
    else
      render :action => 'new'
    end
  end


  def update
    @drivers = Driver.all
    @parcel = Parcel.find(params[:id])
    if @parcel.update_attributes(parcel_params)
    # Handle a successful update.
    else
      render 'edit'
    end
  end
  
  private
  def parcel_params
    params.require(:parcel).permit(:name,:parcel_details,:address,:province,:city, :postal_code, :tracking_number, :customer_id, :tracker_id)
  end

end

app/controllers/plainpage_controller.rb
class PlainpageController < ApplicationController

  def index
    flash[:success ] = "Success Flash Message: Welcome to GentellelaOnRails"
    #other alternatives are
    # flash[:warn ] = "Israel don't quite like warnings"
    #flash[:danger ] = "Naomi let the dog out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parcel_helper.rb
module ParcelHelper
end

app/helpers/parcels_helper.rb
module ParcelsHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => "form-horizontal parcel" } do |f| %>

  <% if @customer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@customer.errors.count, "error") %> prohibited this parcel from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="row" style="background-color: aliceblue">

    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :name, :class => 'control-label col-lg-2' %>
      </div>
      <div class="col-lg-12">
        <%= f.text_field :name, :value => @customer.name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:name) %>
    </div>
    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :surname, :class => 'control-label col-lg-2' %>
      </div>
      <div class="col-lg-12">
        <%= f.text_field :surname, :value => @customer.surname, :class => 'form-control' %>
      </div>
      <%=f.error_span(:surname) %>
    </div>
    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :phone, :class => 'control-label col-lg-2' %>
      </div>
      <div class="col-lg-12">
        <%= f.text_field :phone, :value => @customer.phone, :class => 'form-control' %>
      </div>
      <%=f.error_span(:phone) %>
    </div>      
    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :email, :class => 'control-label col-lg-2' %>
      </div>
      <div class="col-lg-12">
        <%= f.text_field :email, :value => @customer.email, :class => 'form-control' %>
      </div>
      <%=f.error_span(:email) %>
    </div>
    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :address, :class => 'control-label col-lg-2' %>
      </div>
      <div class="col-lg-12">
        <%= f.text_field :address, :value => @customer.address, :class => 'form-control' %>
      </div>
      <%=f.error_span(:address) %>
    </div>
    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :address, :class => 'control-label col-lg-2' %>
      </div>
      <div class="col-lg-12">
        <%= f.text_field :address, :value => @customer.address, :class => 'form-control' %>
      </div>
      <%=f.error_span(:address) %>
    </div>
    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :province, :class => 'control-label col-lg-2' %>
      </div>
      <div class="col-lg-12">
        <%= f.text_field :province, :value => @customer.province, :class => 'form-control' %>
      </div>
      <%=f.error_span(:province) %>
    </div>
    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :city, :class => 'control-label col-lg-2' %>
      </div>
      <div class="col-lg-12">
        <%= f.text_field :city, :value => @customer.city, :class => 'form-control' %>
      </div>
      <%=f.error_span(:city) %>
    </div>
    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :postal_code, :class => 'control-label col-lg-2' %>
      </div>
        <div class="col-lg-12">
          <%= f.text_field :postal_code, :value => @customer.postal_code, :class => 'form-control' %>
        </div>
        <%=f.error_span(:postal_code) %>
    </div>

    <div class="form-group col-lg-6">
      <div class="col-lg-12">
        <%= f.label :customer_id, :class => 'control-label col-lg-2' %>
      </div>
      <div class="col-lg-10">
	<% if controller.controller_name == "customer" && controller.action_name == "new" %>
          <%= f.text_field :customer_id, :value =>  @client_number , :class => 'form-control' %>
	<% else %>
	  <%= f.text_field :customer_id, :value => @customer.customer_id, :class => 'form-control' %>
	<% end %>
      </div>
      <%=f.error_span(:customer_id) %>
    </div>  
  </div>

  <div class="form-group">
    <div class="col-lg-offset-5 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      parcels_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <%= link_to t('customers', :default => "List Customers"),
      "customers",
      :class => 'btn btn-primary' %>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_title">
            <h2>Customer Details</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
	  <div>
	    <%= render :partial => 'form' %>
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/customers/index.html.erb
<%- model_class = Customer -%>

<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    
    <div class="row">
            
      <%= link_to t('.new', :default => t("helpers.links.new")),
      new_customer_path,
      :class => 'btn btn-primary' %>

      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:id) %></th>
            <th><%= model_class.human_attribute_name(:customer_id) %></th>
            <th><%= model_class.human_attribute_name(:name) %></th>
            <th><%= model_class.human_attribute_name(:surname) %></th>
            <th><%= model_class.human_attribute_name(:phone) %></th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= link_to customer.id, customer_path(customer) %></td>
            <td><%= customer.customer_id %></td>
            <td><%= customer.name %></td>
            <td><%= customer.surname %></td>
            <td><%= customer.phone %></td>
            <td>
	      <a href="/customers/<%= customer.id %>"> view all parcels </a>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(customer), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(customer),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>    
  </div>
</div>
<!-- /page content -->

app/views/customers/new.html.erb
<%- model_class = Customer -%>

<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <%= link_to t('customers', :default => "List Customers"),
      "customers",
      :class => 'btn btn-primary' %>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_title">
            <h2>Delivery Sheet</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
	  <div>
	    <%= render :partial => 'form' %>
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/customers/show.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    
    
    <div class="row">
      <%= link_to t('customers', :default => "List Customers"),
      "customers",
      :class => 'btn btn-primary' %>
 
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_title">
            <h2>Delivery Sheet</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
	  <div>
	    <%= render :partial => 'form' %>
	  </div>
	  <div class="clearfix"></div>
	  <div class="row">
	    <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">		
		<div class="x_title">
		  <h2>Parcels</h2>
                  
                  <%= link_to t('.new', :default => t("helpers.links.new")),
                      new_parcel_path(@parcel, :customer_id =>  @customer.id ), :class => 'btn btn-primary pull-right' %>
                  
		  <table class="table table-striped">
		    <thead>
		      <tr>
			<th>parcel id</th>
			<th>parcel name</th>
			<th>parcel details</th>		
		      </tr>
		    </thead>
		    <tbody>
		      <% @parcels.each do |parcel| %>
		      <tr>
			<td><%= link_to parcel.parcel_id, parcel_path(parcel) %></td>
			<td><%= parcel.name %></td>
			<td><%= parcel.parcel_details %></td>
			<td>
			  <a href="/trace/<%= parcel.parcel_id%>"> trace </a>
			  <%= link_to t('.edit', :default => t("helpers.links.edit")),
			  edit_parcel_path(parcel), :class => 'btn btn-primary' %>
			</td>
		      </tr>
		      <% end %>
		    </tbody>
		  </table>
		</div>
	      
	      </div>
	    </div>
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>
  <!-- /page content -->
  

app/views/customers/update.html.erb
<%- model_class = Parcel -%>

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <%= link_to t('customers', :default => "List Customers"),
      "customers",
      :class => 'btn btn-primary' %>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_title">
            <h2>Customer Details</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
	  <div>
	    <%= render :partial => 'form' %>
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/drivers/code.html.erb
<%- model_class = Driver -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:driver_id) %>:</strong></dt>
  <dd><%= @driver.driver_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @driver.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:surname) %>:</strong></dt>
  <dd><%= @driver.surname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @driver.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @driver.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @driver.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:creation_time) %>:</strong></dt>
  <dd><%= @driver.creation_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:modified_time) %>:</strong></dt>
  <dd><%= @driver.modified_time %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
    drivers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_driver_path(@driver), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    driver_path(@driver),
    :method => 'delete',
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-danger' %>
%>

app/views/drivers/index.html.erb
<%- model_class = Driver -%>

<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      
      <%= link_to t('.new', :default => t("helpers.links.new")),
      new_driver_path,
      :class => 'btn btn-primary' %>
      
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
	  <div class="x_title">
            <h2>All Drivers</h2>         
	    
	    <table class="table table-striped">
              <thead>
		<tr>
		  <th><%= model_class.human_attribute_name(:id) %></th>
		  <th><%= model_class.human_attribute_name(:driver_id) %></th>
		  <th><%= model_class.human_attribute_name(:name) %></th>
		  <th><%= model_class.human_attribute_name(:surname) %></th>
		  <th><%= model_class.human_attribute_name(:phone) %></th>
		  <th><%= model_class.human_attribute_name(:address) %></th>
		  <th><%= model_class.human_attribute_name(:email) %></th>
		  
		  <th><%=t '.actions', :default => t("helpers.actions") %></th>
		</tr>
              </thead>
              <tbody>
		<% @drivers.each do |driver| %>
		<tr>
		  <td><%= link_to driver.id, driver_path(driver) %></td>
		  <td><%= driver.driver_id %></td>
		  <td><%= driver.name %></td>
		  <td><%= driver.surname %></td>
		  <td><%= driver.phone %></td>
		  <td><%= driver.address %></td>
		  <td><%= driver.email %></td>
		  <td>
		    <%= link_to t('.edit', :default => t("helpers.links.edit")),
		    edit_driver_path(driver), :class => 'btn btn-default btn-xs' %>
		    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
		    driver_path(driver),
		    :method => :delete,
		    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
		    :class => 'btn btn-xs btn-danger' %>
		  </td>
		</tr>
		<% end %>
              </tbody>
	    </table>
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>

app/views/parcels/index.html.erb
<%- model_class = Parcel -%>

<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    
    
    <div class="row">
      <%= link_to t('parcels', :default => "List Parcels"),
      "parcels",
      :class => 'btn btn-primary' %>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
	  <div class="x_title">
            <h2>All Parcels</h2>         
	    
	    <table class="table table-striped">
	      <thead>
		<tr>
		  <th><%= model_class.human_attribute_name(:id) %></th>
		  <th><%= model_class.human_attribute_name(:parcel_id) %></th>
		  <th><%= model_class.human_attribute_name(:name) %></th>
		  <th><%= model_class.human_attribute_name(:parcel_details) %></th>
                  <th><%= model_class.human_attribute_name(:delivered_flag) %></th>
		  <th><%=t '.actions', :default => t("helpers.actions") %></th>
		</tr>
	      </thead>
	      <tbody>
		<% @parcels.each do |parcel| %>
		<tr>
		  <td><%= link_to parcel.id, parcel_path(parcel) %></td>
		  <td><%= parcel.parcel_id %></td>
		  <td><%= parcel.name %></td>
		  <td><%= parcel.parcel_details %></td>
                  <td><%= parcel.delivered_flag %></td>
                  <td>
		    <%= link_to t('.edit', :default => t("helpers.links.edit")),
		    edit_parcel_path(parcel), :class => 'btn btn-default btn-xs' %>
		    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
		    parcel_path(parcel),
		    :method => :delete,
		    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
		    :class => 'btn btn-xs btn-danger' %>
		  </td>
		</tr>
		<% end %>
	      </tbody>
	    </table>
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>